server:
  port: 8005
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      group-id: voucher-consumer-elastic-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  elasticsearch:
    uris: http://localhost:9200