server:
  port: 8098
logging:
  level:
    root: INFO
    com.example: DEBUG
spring:
  application:
    name: music-event-producer
  config:
    activate:
      on-profile: dev
  kafka:
    topic: music-events
    producer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      properties:

    admin:
      properties:
        bootstrap.servers: localhost:9092, localhost:9093, localhost:9094
        retries: 2
        retry.backoff.ms: 1000