version: '2.1'

services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zookeeper1
    container_name: zookeeper1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888
    networks:
      - elk

  kafka1:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper1
    networks:
      - elk

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.5.2
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./log/:/usr/share/filebeat/log/:ro  # Mount the local log directory
    depends_on:
      - kafka1
    command: filebeat -e -d "*"
    networks:
      - elk

  kafka-ui-web:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui-web
    depends_on:
      - kafka1
    ports:
      - "8080:8080"
    restart: "no"
    environment:
      - KAFKA_CLUSTERS_0_NAME=new-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:19092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper1:2181
      - KAFKA_CLUSTERS_0_READONLY=false
    networks:
      - elk

  elasticsearch:
    image: elasticsearch:8.5.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - elk

  logstash:
    image: logstash:8.5.2
    ports:
      - "5044:5044"
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=123123
      - TZ=Asia/Jakarta
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash.conf:/usr/share/logstash/config/logstash.conf
    networks:
      - elk

  kibana:
      image: kibana:8.5.2
      ports:
        - 5601:5601
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        - ELASTICSEARCH_USERNAME=kibana_user
        - ELASTICSEARCH_PASSWORD="123123"
      networks:
        - elk

volumes:
  es-data:

networks:
  elk:
    driver: bridge




