FROM confluentinc/cp-kafka-connect:7.3.2

# Alternative manual installation of Debezium MySQL connector
RUN mkdir -p /usr/share/java/debezium
RUN curl -sSL https://repo1.maven.org/maven2/io/debezium/debezium-connector-mysql/2.2.0.Final/debezium-connector-mysql-2.2.0.Final-plugin.tar.gz | tar -xvz -C /usr/share/java/debezium
