apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: scram-user
  namespace: kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Read
